### ISSUE TITLE
Configuración inicial

### ISSUE THREAD

**Issue by patrigarcia** [igrowker/i002-decamino-front#13]
1. Clonar el repositorio, instalar las dependencias y configurar el entorno de desarrollo en local.
2. Configurar ruteo y navegación.
3. Actualizar el README con los pasos para la instalación.

**Comment by ArceFacundo2022** [comment]
1) - Configuraciones completadas:
* Dependencias instaladas (Tailwind, Next.UI, Axios, Redux Toolkit, react-icons, react-infinite-scroll-component, sonner, sweetalert2, etc.)
* Organizacion de carpetas
* Fuentes, colores, iconos, imagenes, etc.

2) - Navegacion y rutas de las paginas de la web

3) - Readme diseñado explicando como ejecutar la aplicación y link del despliegue a producción cuando este desplegado
